module.exports = {
    community: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
        {
            type: 'link',
            href: 'https://t.me/hentaiOSchat',
            label: 'Chat with us on Telegram',
        },
    ],
};
