export default {
  sidebar: [
    'devtech',
    {
      'Google': [
        { type: 'autogenerated', dirName: 'google' },
        {
          type: 'link',
          href: 'https://t.me/hentaiOSRaviole',
          label: 'Brooksea Support Chat',
        },
      ],
      'Xiaomi': [
        { type: 'autogenerated', dirName: 'ximi' },
        {
          type: 'link',
          href: 'https://t.me/hentaiOSkona',
          label: 'Gourami Support Chat',
        },
      ]
    },
  ],
};
